[meta_data]
updated_on = 2024-03-27

[pruefidentifikatoren]
"⚠️ No Prüfidentifikatoren found" = "No AHB documents found. Probably there are no AHB in the docx format in the provided path /Users/kevin/workspaces/hochfrequenz/edi_energy_mirror/edi_energy_de/FV2110."
