name: "checks"

on: [pull_request]
jobs:
  checks:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
        check:
          - name: test
            run: uv run --group test pytest --cov kohlrahbi --cov-report term-missing --cov-fail-under 79
          - name: lint
            run: uv run --group lint pylint src/kohlrahbi
          - name: formatting
            run: |
              uv run --group formatting black --check src/kohlrahbi unittests
              uv run --group formatting isort --check src/kohlrahbi unittests
          - name: typecheck
            run: uv run --group typecheck mypy src/kohlrahbi unittests --strict
          - name: spelling
            run: uv run --group spelling codespell src/kohlrahbi README.md
    name: ${{ matrix.check.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run ${{ matrix.check.name }}
        run: ${{ matrix.check.run }}
