name: "test"

on: [ push ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.12" ]
        tox-env: [ "test" ]
    name: ${{ matrix.tox-env }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run ${{ matrix.tox-env }} via Tox
        run: |
          tox -e ${{ matrix.tox-env }}
